arb-dir: lib/application/l10n
output-dir: lib/application/l10n/gen
template-arb-file: app_ja.arb
output-localization-file: app_localizations.dart
preferred-supported-locales:
  - ja
  - en
synthetic-package: false
nullable-getter: false
format: true
