name: search_repositories_on_github
description: "A Flutter app to search GitHub repositories with query."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ^3.27.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter

  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  freezed: ^2.5.7
  go_router_builder: ^2.7.3
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  test: ^1.25.8

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  ios: true
  image_path: "assets/icons/icon.png"
  android: true
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icon-adaptive.png"
  adaptive_icon_background: "#ffffff"